Fixes Quoting in the Mongo User Provider
Previously, mongo user commands would fail due to misquoting of
commands:

Error: /Stage[main]/Openshift_origin::Db::Mongo/Mongodb::Db
[openshift_broker]/Mongodb_user[openshift]: Could not evaluate:
Execution of '/bin/mongo openshift_broker --quiet --eval
db.system.users.find({user:"openshift"}).count()' returned 252:
Thu Mar 20 20:23:10.633 count failed: { "note" :
"from execCommand", "ok" : 0, "errmsg" : "not master" }
at src/mongo/shell/query.js:180

In the example above, the openshift user should be in single
quotes.  Using the mongo shell command using double quotes further
explains the error:

ReferenceError: openshift is not defined